Update customChange.yml

diff --git a/.github/workflows/customChange.yml b/.github/workflows/customChange.yml
--- a/.github/workflows/customChange.yml
+++ b/.github/workflows/customChange.yml
@@ -118,13 +118,13 @@ jobs:
     steps:
       - name: Run deployment scripts
         run: echo Completed Deployment currently in post_change state.
-      - name: Failing step
-        id: demo
-        run: exit 1
-      - name: The demo step has failed
-        # if: ${{ failure() && steps.demo.conclusion == 'failure' }}
-        if: ${{ always() }}
-        run: echo After failure step.
+      # - name: Failing step
+      #   id: demo
+      #   run: exit 1
+      # - name: The demo step has failed
+      #   # if: ${{ failure() && steps.demo.conclusion == 'failure' }}
+      #   if: ${{ always() }}
+      #   run: echo After failure step.
 #   integrationTest:
 #     needs: deploy
 #     name: Integration Tests
